### ISSUE TITLE
Время ответа на вопрос

### ISSUE THREAD

**Issue by Doreti** [avaika/interview#2]
время на вопрос должно задаваться в районе 15-20 секунд на ответ, чтобы отсечь возможность списать/нагуглить ответ в интернете. после окончания таймера вопрос помечается как не решенный.  Есть идея что можно сделать интерактивный таймер, в котором время будет меняться в зависимости от сложности вопроса - есть он совсем простой, то можно уменьшать время до 10 секунд т.к. ответы на некоторые вопросы гугл выдает на первой страницы и шанс списать за 15-20 секунд увеличивается 
Задача для бота

**Comment by avaika** [comment]
кто ты? :)
и про какого бота здесь идёт речь?

и нет никакого смысла засекать строго время. если ответ на вопрос гуглится одним запросом, то стоит подумать нужен ли такой вопрос. а если он не гуглится одним запросом, то и засекать не нужно ничего.
ну если только не машина человека собеседует. что странно.
