### ISSUE TITLE
Отчеты

### ISSUE THREAD

**Issue by Doreti** [avaika/interview#3]
необходимо отправлять отчет после прохождения теста hr. Отчет должен содержать статистику по темам, общей результат, время решения всего теста,  среднее время ответа на один вопрос. Отчет можно отправлять в телеграм, зная ник hr. Так же можно реализовать механизм для групповой отправки всем hr либо персонального просмотр. 
Задача для бота

**Comment by avaika** [comment]
won't do. need to reports.
